from ..serialization import *
from ..runtime import *
PARACMPT_PARAMETRIC_COMPONENT = 'BPParametricComponent'
PARACMPT_KEYWORD_REPRESENTATION = '\a_representation'
PARACMPT_KEYWORD_SOURCE = '\a_source'
PARACMPT_KEYWORD_NAME = '\a_name'
PARACMPT_KEYWORD_PARENT = '\a_parent'
PARACMPT_KEYWORD_SCHEMA_NAME = '\a_schema_name'
PARACMPT_KEYWORD_CLASS_NAME = '\a_class_name'
PARACMPT_KEYWORD_INFORMATION = '\a_information'
PARACMPT_KEYWORD_PREVIEW_VIEW = '\a_preview_view'
PARACMPT_KEYWORD_PREVIEW_IMAGE = '\a_preview_image'
PARACMPT_KEYWORD_TRANSFORMATION = '\a_transformation'
PARACMPT_KEYWORD_TAIJI = '\a_taiji'
PARACMPT_KEYWORD_STYLE = '\a_material'
PARACMPT_KEYWORD_EXTRACT_GRAPHICS = '\a_extract_graphics'
PARACMPT_KEYWORD_DEPENDENT_FILE = '\a_dependent_file'
PARACMPT_KEYWORD_REPLACE = 'replace'
PARACMPT_KEYWORD_INTERACT = 'interact'
PARACMPT_KEYWORD_OBVIOUS = 'obvious'
PARACMPT_KEYWORD_PIVOTAL = 'pivotal'
PARACMPT_KEYWORD_READONLY = 'readonly'
PARACMPT_KEYWORD_SHOW = 'show'
PARACMPT_KEYWORD_GROUP = 'group'
PARACMPT_KEYWORD_DESCRIPTION = 'description'
PARACMPT_KEYWORD_MODIFIED = '\a_modified'
PARACMTP_PLACE_TOOL_EXIT = 'place_tool_exit'
PARACMTP_PLACE_TOOL_DYNAMIC = 'place_tool_dynamic'
PARACMPT_SPHERE_TO_GRAPHICS = '\a_sphere_to_graphics'
PARACMPT_SPHERE_UPPER = 'upper'
PARACMPT_SPHERE_LOWER = 'lower'
PARACMPT_POINT_TO_GRAPHICS = '\a_point_to_graphics'
PARACMPT_ARC_TO_GRAPHICS = '\a_arc_to_graphics'
PARACMPT_ARC_SCOPE = 'scope'
PARACMPT_LINE_TO_GRAPHICS = '\a_line_to_graphics'
PARACMPT_LINE_PARTS = 'parts'
PARACMPT_SPLINE_CURVE_PARTS = 'parts'
PARACMPT_PARAMETRIC_EQUATION_PARTS = 'parts'
PARACMPT_SECTION_TO_GRAPHICS = '\a_section_to_graphics'
PARACMPT_SECTION_PARTS = 'parts'
PARACMPT_SECTION_COLSE = 'colse'
PARACMPT_CUBE_TO_GRAPHICS = '\a_cube_to_graphics'
PARACMPT_LOFT_TO_GRAPHICS = '\a_loft_to_graphics'
PARACMPT_LOFT_PARTS = 'parts'
PARACMPT_LOFT_SMOOTH = 'smooth'
PARACMPT_SWEEP_TO_GRAPHICS = '\a_sweep_to_graphics'
PARACMPT_SWEEP_SECTION = 'section'
PARACMPT_SWEEP_TRAJECTORY = 'trajectory'
PARACMPT_SWEEP_SMOOTH = 'smooth'
PARACMPT_COMBINE_TO_GRAPHICS = '\a_combine_to_graphics'
PARACMPT_COMBINE_PARTS = 'parts'
PARACMPT_FUSION_TO_GRAPHICS = '\a_fusion_to_graphics'
PARACMPT_FUSION_PARTS = 'parts'
PARACMPT_INTERSECT_TO_GRAPHICS = '\a_intersect_to_graphics'
PARACMPT_INTERSECT_PARTS = 'parts'
PARACMPT_TEXT_TO_GRAPHICS = '\a_text_to_graphics'
PARACMPT_TEXT_TEXT = 'text'
PARACMPT_ARRAY_TO_GRAPHICS = '\a_array_to_graphics'
PARACMPT_ARRAY_ONTOLOGY = 'ontology'
PARACMPT_ARRAY_PARTS = 'parts'
PARACMPT_STYLE_VERSION = 'version'
PARACMPT_SYMBOLOGY_COLOR = 'color'
PARACMPT_MATERIAL_NAME = 'name'
PARACMPT_FONT_NAME = 'font name'
PARACMPT_FONT_TYPE = 'font type'
PARACMPT_FONT_SIZE = 'font size'
PARACMPT_FONT_HORZ_SCALE = 'horz scale'
PARACMPT_FONT_VERT_SCALE = 'vert scale'
PARACMPT_GET_VERSION = 'get_version'
PARACMPT_INTERACT_ROTATE = 'interact_rotate'
PARACMPT_INTERACT_LINER = 'interact_liner'
PARACMPT_INTERACT_MULTIPOINT = 'interact_multi_point'
PARACMPT_PACK_BFA = 'pack_bfa'
PARACMPT_GET_TEMP_PATH = 'get_temp_path'
PARACMPT_PLACE_INSTANCE = 'place_instance'
PARACMPT_GETDATA_INSTANCE = 'get_data_instance'
PARACMPT_PLACEDATA_INSTANCE = 'place_data_instance'
PARACMPT_PLACE_INSTANCE_TO = 'place_instance_to'
PARACMPT_CREATE_GEOMETRY = 'create_geometry'
PARACMPT_CREATE_MATERIAL = 'create_material'
PARACMPT_UPDATE_MATERIAL = 'update_material'
PARACMPT_CREATE_BSPLINEPOINTS = 'create_bsplinepoints'
PARACMPT_SET_ENTITY_PROPERTY = "set_entity_property"
PARACMPT_GET_MODELID_ENTITYID_RELATION = "get_modelid_entityid_relation"
PARACMPT_GET_ENTITY_PROPERTY = "get_entity_property"
PARACMPT_GET_ALL_ENTITYPROPERTY = "get_all_entity_property"
PARACMPT_DELETE_ENTITY = "delete_entity"
PARACMPT_CREATE_INSTANCE_INSTANCEKEY= "create_instance_instancekey"
PARACMPT_DELETE_INSTANCE_BYINSTANCEKEY = "delete_instance_byinstancekey"
PARACMPT_BIND_ENTITY_INSTANCE= "bind_entity_instance"
PARACMPT_REMOVEBIND_ENTITY_INSTANCE= "removebind_entity_instance"
PARACMPT_GET_ALLBINDING_ENTITY_FROM_INSTANCE= "get_allbinding_entity_from_instance"
PARACMPT_GET_ALL_INSTANCEKEY= "get_all_instancekey"
PARACMPT_GET_MODELID_FROM_INSTANCE= "get_modelid_from_instance"
PARACMPT_GET_INSTANCEKEY_FROM_ENTITY= "get_instancekey_from_entity"
PARACMPT_PICKUP_ENTITYID_AND_INSTANCEKEY= "pickup_entityid_and_instancekey"
PARACMPT_GET_NOUMENON_FROM_INSTANCEKEY= "get_noumenon_from_instancekey"
PARACMPT_GET_ENTITYID_FROM_BOXSELECTION= "get_entityid_from_boxselection"
PARACMPT_GET_LINE_FROM_CURVEARRAY="get_line_from_curvearray"
PARACMPT_DELETE_ONE_ENTITY = "delete_one_entity"
PARACMPT_GET_LINE_FROM_CURVEARRAY="get_line_from_curvearray"
PARACMPT_REPLACE_NOUMENON = "replace_noumenon"
PARACMPT_GET_VIEW_SCALE= "get_view_scale"
# new class
PARACMPT_SPLINECURVE_TO_GRAPHICS= "\a_spline_curve_to_graphics"
PARACMPT_SPLINECURVE_POINTS="control_points"
PARACMPT_SPLINECURVE_K="order_k"
PARACMPT_SPLINECURVE_NUM="discrete_num"
PARACMPT_SPLINECURVE_TYPE="spline_type"
PARACMPT_PARAMETRICEQUATION_TO_GRAPHICS= "\a_parametric_equation_to_graphics"
PARACMPT_PARAMETRICEQUATION_X="para_equa_x"
PARACMPT_PARAMETRICEQUATION_Y="para_equa_y"
PARACMPT_PARAMETRICEQUATION_Z="para_equa_z"
PARACMPT_PARAMETRICEQUATION_T="step_t"
PARACMPT_PARAMETRICEQUATION_FUN="para_fun"

